name: linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Setup Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install system libraries
        run: |
          sudo apt update
          sudo apt install -y libxinerama-dev libxcursor-dev libxi-dev libgl-dev

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.224.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang
          vulkan-use-cache: true

      - name: Build Tests
        working-directory: tests
        run: |
          threads=`nproc`
          cmake .
          make -j $threads

      - name: Test
        working-directory: tests
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: |
          ctest --verbose
